### ISSUE TITLE
Almost perfect reconstructions but random samples

### ISSUE THREAD

**Issue by pabloppp** [openai/vdvae#10]
I tried to reproduce this paper using a custom dataset, but after just 1 epoch I already see almost perfect reconstructions while sampling from the normal distributions gives random noisy results. It would seem like either the model is ignoring all encodings except the ones at higher resolution, or the model fails to encode things into a normal distribution, which doesn't seem the case since the KL loss is low and decreasing...
![image](https://user-images.githubusercontent.com/4237014/114300959-def71600-9ac2-11eb-9f44-e5b46a20c79c.png)
Is this something to be expected? How would I go about improving these results?
Thanks!

**Comment by christopher-beckham** [comment]
what is the exact value of your KL loss? do you have plots?

You also might need to upweight `beta` by instead optimising the loss: `nll + beta*kl` instead. The original code and paper has no coefficient for either term, so `beta` is assumed to be 1. I think such a coefficient should be added to the code.

**Comment by pabloppp** [comment]
I am using a custom implementation. For example, I am using L2 loss as the reconstruction term, so my loss values might not be comparable to the ones from the paper, but my KL loss was about 0.05. Unfortunately I have no plots.

I actually tried what you mentioned and increased the weight of the KL term, first x10 then x100 and I saw a decrease of the reconstruction quality (which I guess is expected), but also what I believe is an improvement of the sampling quality
<img width="1352" alt="Captura de pantalla 2021-04-12 a las 23 26 34" src="https://user-images.githubusercontent.com/4237014/114464801-8751cb00-9be6-11eb-8dd8-274226ea963a.png">
Still far from realistic results, but definitely an improvement 🤔 not sure if it just needs more training time, or there is a limit of what the sampling results can achieve.

**Comment by christopher-beckham** [comment]
I think maybe it's a matter of letting it train for longer. Perhaps you could easily gauge if the quality is still improving either by periodically evaluating the FID on the prior-sampled sampled images or evaluating the ELBO (`nll + kl`) on those images. I would expect the ELBO to be much higher on gibberish images than reconstructions or real images.

It also depends on how big your dataset is. If it's too small you should not expect to get much generalisation.

**Comment by pabloppp** [comment]
Thanks, @christopher-beckham I also thought that it might be a matter of letting it train for longer.
I am currently just saving an output every epoch and evaluating the quality visually. I also moved to another dataset to see if one of the issues was the high variance on the one I was using. 
I'll close this issue for now, hopefully I will eventually achieve good results! 
Thanks again
