### ISSUE TITLE
How to check bits per dim from the logs

### ISSUE THREAD

**Issue by jsikyoon** [openai/vdvae#5]
Hi authors!

Thank you for your sharing!

I am wondering how I can check the bits per dim from the logs, when quickly reviewing the code, distortion is that, but when I ran, distortion is too small as thinking it BPD (about 1).

Could I know that?

Bests, Jaesik.

**Comment by rewonc** [comment]
Bits per dim will be the ELBO divided by ln(2). (It's logged in nats per dim).  The elbo is the rate + distortion.

**Comment by jsikyoon** [comment]
There is no log for nats per dim (is it the log 'rate'?)

but I am testing with cifar10,  elbo / rate is about 2.03 

bests, Jaesik.

**Comment by rewonc** [comment]
`elbo = rate + distortion`.  What's reported in papers is the elbo. The code logs `elbo` in `nats/dim`, and you can convert this to `bits/dim` by computing `elbo/ln(2)`. Does that make sense?

**Comment by jsikyoon** [comment]
Yes, I understood, thanks!

Bests, Jaesik.
