### ISSUE TITLE
input data shift and scale

### ISSUE THREAD

**Issue by jsikyoon** [openai/vdvae#6]
Hi authors!

I have a question about input image shift and scale. 

The shift and scale for the output data are reasonable [0,255] -> [-1,1], but you used various numbers for input shift and scale for the different datasets.

Could I know the reference of the values? 

Or found through fine-tuning?

Bests, Jaesik.

**Comment by rewonc** [comment]
They're the mean / standard deviation of (if I recall correctly) 10k samples from the training set. The values make the inputs, on average, zero mean and unit variance.

**Comment by jsikyoon** [comment]
thanks!
